### ISSUE TITLE
Authorize button is unresponsive

### ISSUE THREAD

**Issue by JustApu** [beckf/lightspeed-vc-connector#38]
I've entered our Settings, saved them, quit from the program and then reopened it. But the "Authorize" button is not doing anything for me. Thoughts?

I don't need a refresh token myself, correct? That comes from Lightspeed as part of the authorization process?

Python 3.8.3 on MacOS

Thanks in advance,

Apu
<img width="775" alt="Screen Shot 2020-06-15 at 22 01 59" src="https://user-images.githubusercontent.com/30990146/84723757-59631200-af54-11ea-8ed0-076ad5b36b01.png">

**Comment by beckf** [comment]
All of the python binaries and dependencies are bundled up in the app.  The authorization part requires webkit which is what makes the project so large.  

Did you make sure to have your redirect URI set to localhost?  The authorize function will grab the refresh token from that url.  

Do you get the popup error that reads: "Make sure Lightspeed developer client id, secret, and account number has been saved."

You can verify the settings in the settings window by unmasking the fields.  This can be done by pressing Ctrl+Shift+R on the settings tab.  Make sure the data is correct without spaces.

Lastly, is this on Catalina?  I am working to get this working for Catalina and with its new requirements for notarization.

**Comment by beckf** [comment]
Sorry - That is Command-Shift-R

**Comment by JustApu** [comment]
New info:
I get no pop-up or any indication that clicking "Authorize" is doing anything. In fact, now that I play with it more, none of the buttons work. The tabs work (I can go from Settings to Authorize App, etc.) but I cannot Save Log, Change Password or Authorize.

The original "Save Settings" button must have worked originally since my Settings to reappear each time I launch the program. However, it no longer works; if I make a change to the settings and click that button, nothing happens. If I quit and come back, my original settings are still present.

I do get some SyntaxWarnings about is vs == but fixing those lines of code does not seem to have any effect. There was also a "QFont::setPointSize: Point size <= 0 (-1), must be greater than 0" error but changing that value in mainwindow.py just makes the error message go away; the UI problem remains.


Answers to your questions:
High Sierra (10.13.5) with Python 3 from https://www.python.org/downloads/release/python-383/ I do have a separate Catalina machine I was going to try tomorrow but have not yet.

I had the redirect set to https://localhost but changed it to http://localhost with no difference.

The settings appear to be correct; I used Command-Shift-R to reveal the hidden settings and then copy-and-pasted them back into the Lightspeed OAuth login page and got back to the settings I had originally entered.

**Comment by beckf** [comment]
OK - Are you running from source or the precompiled app?  If from source, I just pushed a new requirements file to master.  Pull that and update your env.  I have not yet fully tested python 3.8. I do see a typo in one of the merge comments that mentions python 3.8, but I believe this was intended to be 3.6.8.  

Catalina does work under these conditions for me.

**Comment by beckf** [comment]
It appears that Lightspeed has changed something in their response.  I will investigate and fix this week.

**Comment by beckf** [comment]
Actually - I just turned up a new demo site and was able to authorize without any issues.  It sounds like you have something else going on by not having the buttons work. 

Lets start over - 

Is this the compiled application from releases? or from source?  Other schools tend to just use the compiled application.  Perhaps that is the best place to start if this is from source.

Just to confirm, your LS Account ID should only be about 6 digits long.  You can find it in the dropdown where you signout.

**Comment by JustApu** [comment]
From source - download from GitHub as a ZIP. I'm probably ignoring my nose despite my face but where is the compiled binary found?

Thank you!

**Comment by beckf** [comment]
Grab it from releases.
https://github.com/beckf/lightspeed-vc-connector/releases

If you are interested in helping with development then we can get source running.

**Comment by JustApu** [comment]
Brand new Mac running 10.15.5, freshly downloaded release, and never had the source-based distribution running here to minimize the chance of conflicts with anything I installed manually... I get a momentary white screen while it seems to try to load some page then just a gray box.

<img width="1440" alt="Screen Shot 2020-06-23 at 4 37 01 PM" src="https://user-images.githubusercontent.com/30990146/85459565-4c57ab80-b570-11ea-8aab-8df3d7420a24.png">

P.S. I had to "xattr -cr /Applications/LSVCConnector.app" to get the application to run at all. Otherwise, the OS sees it as a damaged application.

**Comment by JustApu** [comment]
FWIW, still no luck getting the Authorize button to work. But I built a standalone OAuth2 authorization client and was able to get the refresh code from Lightspeed and that works in the LSVCConnector. Faculty & Staff are loading into a demo store now, albeit slowly. I'll load students next so I can test everything before bringing them into the real store.

Thanks,

Apu

**Comment by beckf** [comment]
Thanks for the update - I have never had a problem with the authorize button with several other installs.  I wonder if there is something in your environment that is different from mine.  Once things settle, I will try the same steps with a new 10.15.6 machine and try to authorize in a new store.

Creating accounts in LS is a little slow.  It requires an API call for each account and LS has some rate limits enforced.  I have contacted them about this and the rate limits has been increased on my api account.  You should try the same.  It is still a little slow, but helps.

**Comment by beckf** [comment]
I made some small updates to improve stability with Windows and the authorization window.  This was in the last merge #47 .  Hopefully this has fixed your issue listed here.
