### ISSUE TITLE
Credit limits

### ISSUE THREAD

**Issue by JustApu** [beckf/lightspeed-vc-connector#40]
Can we customize the credit limits? For example, while we want to sync Faculty & Staff so it is easier to handle their purchases, they do not have any school credit (cash, check or credit card only). On the other hand, we want Students to have a credit line but want to limit their spending per month so mom & dad don't get a huge surprise when they see their next invoice.

Apu

**Comment by JustApu** [comment]
Semi-related: default discount code customization would be nice. There is an "employee" discount for faculty & staff in our store so it would be nice to be able to set that field as part of the customer creation as well.

**Comment by beckf** [comment]
This is totally doable.  What do you think about an "import options" tab?  We would need to establish a mapping to this data in advance.  Let me look through some options, and report back.

**Comment by JustApu** [comment]
Import Options would be great. Thanks!

**Comment by beckf** [comment]
Try this version and let me know what you see.  The binary is located here:
https://github.com/beckf/lightspeed-vc-connector/releases/tag/v1.20

If this works, we can build out more parts to import options.

**Comment by beckf** [comment]
Try this one instead. I discovered a pyinstaller issue was keeping it from running. 

https://github.com/beckf/lightspeed-vc-connector/releases/tag/v1.21

**Comment by JustApu** [comment]
1.21 works here.  Only had a couple of new people to sync but they came over properly.

Thanks, Forrest.

**Comment by beckf** [comment]
Updated to incorporate #43 

https://github.com/beckf/lightspeed-vc-connector/releases/tag/v1.22b

**Comment by beckf** [comment]
Sorry @JustApu  - Meant to respond on the Discount code before closing - The discount code is applied to the customer type.  Check here: 
<img width="1197" alt="Screen Shot 2020-09-07 at 7 21 31 PM" src="https://user-images.githubusercontent.com/8514730/92420138-b4656900-f13f-11ea-8e2f-4ad671c0d17b.png">
