### ISSUE TITLE
Similarly named customers

### ISSUE THREAD

**Issue by JustApu** [beckf/lightspeed-vc-connector#42]
It would be nice to be able to import grade level and/or graduation year into a customer record. Especially helpful if we can put an abbreviated version of it into the customer name.

For example, we have a father (teacher) and son (student) with the same name. We have a few students with the same name. Having the grade level in the name would help us choose the correct customer.

Thanks,

Apu

**Comment by beckf** [comment]
Are you able to see the email address in the search field?  We typically use this since our emails for students have a different pattern.
