### ISSUE TITLE
Syncing into the wrong custom field

### ISSUE THREAD

**Issue by JustApu** [beckf/lightspeed-vc-connector#43]
The Veracross ID number and date/time of last sync are flowing into the wrong custom fields.

<img width="689" alt="Screen Shot 2020-08-29 at 16 27 19" src="https://user-images.githubusercontent.com/30990146/91645675-fd693f00-ea14-11ea-8b60-6ea6838e4960.png">

**Comment by beckf** [comment]
The Custom Fields were statically mapped to the first two fields created in the store.  We can add fields to the new import options tab that allows you to specify where these values need to go in Lightspeed.

**Comment by JustApu** [comment]
Thanks, Forrest. I realized that. Thankfully, we had only a handful of manually entered customers so far so I was able to rename the fields in our store and then move the custom field data around before our initial sync.

**Comment by beckf** [comment]
See here: Import Options now allows you to specify which Lightspeed custom field to use.

https://github.com/beckf/lightspeed-vc-connector/releases/tag/v1.22b
